YEAR_PARAPHRASE = {
    1801: 'The year Italian astronomer Giuseppe Piazzi discovered the dwarf planet Ceres',
    1802: 'The year William Cobbett began his weekly Political Register',
    1803: 'The year William Symington demonstrated the Charlotte Dundas, the first practical steamboat',
    1804: 'The year the first steam locomotive began operation',
    1805: 'The year the Third Coalition mobilized against France',
    1806: 'The year Cape Colony became part of the British Empire',
    1807: 'The year the Royal Navy bombarded Copenhagen and seized the Danish fleet',
    1808: 'The year Russia conquered Finland from Sweden during the Finnish War',
    1809: 'The year Beethoven composed his Piano Concerto No. 5, "The Emperor."',
    1810: 'The year the trumpet received its valves',
    1811: 'The year Paraguay declared independence from the Spanish Empire',
    1812: 'The year British Prime Minister Spencer Perceval was assassinated',
    1813: "The year William Hedley's Puffing Billy demonstrated the power of steam locomotives",
    1814: 'The year Elisha Collier invented the flintlock revolver',
    1815: 'The year Jane Austen published Emma in December',
    1816: "The year Shaka's Zulu Kingdom became the largest in Southern Africa",
    1817: 'The year Princess Charlotte of Wales died following childbirth',
    1818: 'The year Mary Shelley published Frankenstein; or, The Modern Prometheus',
    1819: 'The year the case of Trustees of Dartmouth College v. Woodward was decided',
    1820: 'The year witnessed the dissolution of the Maratha Empire in India',
    1821: 'The year the Navarino massacre of Turks living in Greece occurred',
    1824: "The year marked the premiere of Beethoven's Ninth Symphony",
    1825: 'The year the Decembrist revolt in Russia was suppressed',
    1826: 'The year American Samuel Morey patented the internal combustion engine',
    1827: 'The year marked the deaths of William Blake and Ludwig van Beethoven',
    1829: 'The year Gioachino Rossini composed the Italian opera William Tell',
    1830: 'The year marked the opening of the Liverpool and Manchester Railway',
    1831: 'The year a great Bosnian uprising against Ottoman rule occurred',
    1832: 'The year the British Parliament passed the Great Reform Act',
    1833: 'The year the General Trades Union was founded in New York City',
    1834: 'The year the Spanish Inquisition officially ended',
    1835: 'The year the September laws restricted freedom of the press in France',
    1836: 'The year the Battle of the Alamo ended with a defeat for Texan separatists',
    1837: 'The year Charles Dickens published Oliver Twist',
    1838: 'The year Chartism emerged as a working-class reform movement in Britain',
    1839: 'The year the Kingdom of Belgium was declared',
    1840: 'The year Railway Mania swept through the UK and Ireland',
    1841: 'The year the word "dinosaur" was coined by Richard Owen',
    1842: 'The year anesthesia was used for the first time',
    1843: 'The year the short stories A Christmas Carol and The Tell-Tale Heart were published',
    1844: 'The year marked the Dominican War of Independence from Haiti',
    1845: 'The year the New Zealand Wars began',
    1846: 'The year ultraconservative Pope Pius IX battled modernity',
    1847: 'The year the Caste War of Yucatán began',
    1848: 'The year the Second Anglo-Sikh War took place',
    1849: 'The year the safety pin and the gas mask were invented',
    1850: 'The year the Little Ice Age ended around this time',
    1851: 'The year Louis Napoleon assumed power in France via a coup',
    1852: 'The year Balmoral Castle was purchased by the British royal family',
    1854: 'The year the Siege of Sevastopol occurred, and the city fell to French and British forces',
    1855: 'The year cocaine was isolated by Friedrich Gaedcke',
    1856: "The year the world's first oil refinery was established in Romania",
    1857: 'The year the Dred Scott decision denied citizenship to African Americans',
    1858: 'The year Minnesota entered the Union',
    1859: "The year John Brown led a raid on Harpers Ferry",
    1860: 'The year Giuseppe Garibaldi launched the Expedition of the Thousand',
    1861: 'The year the American Civil War began between the Union and the seceding Confederacy',
    1862: 'The year the Pony Express ended its service',
    1863: 'The year an earthquake left Manila in ruins',
    1864: 'The year the Circassian genocide occurred',
    1865: 'The year Gregor Mendel formulated his laws of inheritance',
    1866: 'The year a successful transatlantic telegraph cable was laid',
    1867: 'The year Alfred Nobel invented dynamite',
    1868: 'The year the safety bicycle was invented',
    1869: 'The year Dmitri Mendeleev created the periodic table',
    1870: 'The year the Long Depression began in Western Europe and North America',
    1871: 'The year the Royal Albert Hall opened in London',
    1872: 'The year Yellowstone National Park, the first of its kind, was created',
    1873: 'The year blue jeans and barbed wire were invented',
    1874: 'The year the Home Rule Movement was established in Ireland',
    1875: 'The year 26 million people perished in India due to famine',
    1876: 'The year Bulgarians instigated the April Uprising against Ottoman rule',
    1877: 'The year Asaph Hall discovered the moons of Mars',
    1879: 'The year Thomas Edison tested his first light bulb',
    1880: 'The year the First Boer War began',
    1881: 'The year the Mahdist War broke out in Sudan',
    1882: 'The year the British invaded and subsequently occupied Egypt',
    1883: "The year Robert Louis Stevenson's Treasure Island was published",
    1884: 'The year Germany gained control of Cameroon',
    1885: 'The year Britain established a protectorate over Bechuanaland',
    1886: 'The year Karl Benz sold the first commercial automobile',
    1887: 'The year the British Empire took over Balochistan',
    1888: 'The year the National Geographic Society was founded',
    1889: 'The year Vincent van Gogh painted The Starry Night',
    1890: 'The year the cardboard box was invented',
    1892: 'The year fingerprinting was officially adopted for the first time',
    1893: 'The year the Internal Macedonian Revolutionary Organisation was formed',
    1894: 'The year Karl Elsener invented the Swiss Army knife',
    1895: 'The year French troops captured Antananarivo in Madagascar',
    1896: 'The year the Klondike Gold Rush began in Canada',
    1897: 'The year the term "graveyard shift" was first documented',
    1898: 'The year the United States annexed the Republic of Hawaii',
    1899: 'The year an Indian famine killed over 1 million people',
    1900: 'The year Hawaii became an official U.S. territory',
    1901: 'The year the Australian colonies federated',
    1902: 'The year the Second Boer War ended in a British victory',
    1903: 'The year the Wright brothers achieved the first controlled heavier-than-air flight',
    1904: 'The year the Entente Cordiale was signed between Britain and France',
    1905: 'The year the First Moroccan Crisis began, lasting until April 1906',
    1906: 'The year a magnitude 7.9 earthquake in San Francisco, California, killed 3,000 people',
    1907: 'The year the Persian Constitutional Revolution ended with the establishment of a parliament',
    1908: 'The year that became the coldest since 1880, according to NASA',
    1909: 'The year a countercoup failed in the Ottoman Empire',
    1910: "The year Halley's Comet returned",
    1911: 'The year Ernest Rutherford identified the atomic nucleus',
    1912: 'The year the First Balkan War began',
    1913: 'The year the Federal Reserve System was created',
    1914: 'The year the Panama Canal opened',
    1915: 'The year of the sinking of the RMS Lusitania',
    1916: 'The year Bayerische Flugzeugwerke, which later became BMW, was founded in Germany',
    1917: 'The year the Ukrainian–Soviet War began',
    1918: "The year independence was declared in the West Ukrainian People's Republic",
    1919: 'The year the Treaty of Versailles redrew European borders',
    1920: 'The year the League of Nations was founded',
    1921: 'The year the Ukrainian–Soviet War ended',
    1922: 'The year Howard Carter discovered the tomb of Tutankhamun',
    1923: 'The year Time Magazine was first published',
    1924: 'The year the August Uprising occurred in Georgia against Soviet rule',
    1925: "The year Adolf Hitler's Mein Kampf was published",
    1926: 'The year General Georgios Kondylis overthrew General Theodoros Pangalos in Greece',
    1927: 'The year construction began on Mount Rushmore in South Dakota, U.S',
    1928: 'The year Hassan al-Banna founded the Muslim Brotherhood',
    1929: 'The year Leon Trotsky was exiled',
    1930: 'The year Clyde Tombaugh discovered Pluto',
    1931: 'The year the Chinese Soviet Republic was proclaimed by Mao Zedong',
    1932: 'The year a military coup occurred in Chile',
    1933: 'The year the New Deal began in America',
    1934: 'The year Mao Zedong began the Long March',
    1935: 'The year 20th Century Fox was established',
    1936: 'The year George Nissen and Larry Griswold built the first modern trampoline',
    1937: 'The year the Irish Republican Army attempted to assassinate King George VI',
    1938: 'The year the DC Comics hero Batman made his first appearance',
    1939: 'The year the Molotov–Ribbentrop Pact was signed between Germany and the Soviet Union',
    1940: 'The year neptunium was synthesized',
    1941: 'The year construction on Mount Rushmore ended',
    1942: 'The year the Manhattan Project began',
    1943: 'The year a famine in Bengal killed up to 3 million people',
    1944: 'The year the Chechen insurgency ended with the deportation of the entire Chechen population',
    1945: 'The year the United Nations was founded with the signing of the UN Charter',
    1946: 'The year the French Fourth Republic was established',
    1947: 'The year the Hyundai Group was founded by Chung Ju-yung in Seoul, South Korea',
    1948: 'The year Mahatma Gandhi was assassinated',
    1949: 'The year the First Indo-Pakistani War ended',
    1950: 'The year the Bodo League Massacre of prisoners occurred during the Korean War',
    1951: 'The year Winston Churchill became Prime Minister of the United Kingdom',
    1952: 'The year the Miss Universe pageant was established',
    1953: 'The year the first color television was produced',
    1954: 'The year the Algerian War began',
    1955: 'The year Albert Einstein passed away',
    1956: "The year Gamal Abdel Nasser's nationalization of the Suez Canal triggered the Suez Crisis",
    1957: 'The year Ghana gained independence from Britain',
    1958: 'The year Pizza Hut was founded',
    1959: 'The year the Vietnam War began, which lasted until 1975',
    1960: 'The year the Mau Mau Uprising ended',
    1961: 'The year the assassination of Patrice Lumumba sparked the Congo Crisis',
    1962: 'The year the Cuban Missile Crisis nearly caused a nuclear war',
    1963: "The year Bob Dylan released 'The Freewheelin' Bob Dylan'",
    1964: 'The year the Colombian armed conflict began',
    1965: 'The year the September 30th Movement occurred in Indonesia',
    1966: 'The year the Indonesia–Malaysia confrontation ended',
    1967: 'The year the first high-speed rail was introduced in Tokyo',
    1968: 'The year the Palestinian insurgency in South Lebanon began',
    1969: 'The year Sesame Street premiered its debut episode',
    1970: 'The year Anwar Sadat became President of Egypt',
    1971: 'The year the Third Indo-Pakistani War took place',
    1972: "The year Northern Ireland's Bloody Sunday occurred",
    1973: 'The year the Yom Kippur War took place',
    1974: 'The year the fossil \"Lucy\" (Australopithecus afarensis) was discovered in Ethiopia',
    1975: 'The year Angola declared independence from Portugal and the Angolan Civil War erupted',
    1976: 'The year Mao Zedong passed away',
    1977: 'The year Djibouti gained independence from France',
    1978: 'The year John Paul II became Pope',
    1979: "The year the Vietnamese invasion of Kampuchea ended the Khmer Rouge regime in Cambodia",
    1980: 'The year Vanuatu gained independence',
    1981: 'The year Anwar Sadat was assassinated',
    1982: 'The year Israel withdrew from the Sinai Peninsula',
    1983: 'The year the dictatorship in Argentina ended',
    1984: 'The year the Bhopal disaster occurred',
    1985: 'The year DNA fingerprinting was used for the first time',
    1986: 'The year the first close-up images of the planet Uranus were captured',
    1987: 'The year the antidepressant drug fluoxetine, marketed as Prozac, became commercially available',
    1988: "The year Chile's Augusto Pinochet lost a national plebiscite on his rule",
    1989: 'The year Nicolae and Elena Ceaușescu were tried and executed in Romania',
    1990: 'The year the Contra War ended',
    1991: 'The year Boris Yeltsin became the first President of Russia',
    1992: 'The year the Kuiper belt and the first extrasolar planets were discovered',
    1993: 'The year Bill Clinton was inaugurated as President of the United States',
    1994: 'The year the First Chechen War began',
    1995: 'The year the Third Taiwan Strait Crisis began',
    1996: 'The year the First Congo War began',
    1997: 'The year the first episode of Pokémon aired on TV Tokyo',
    1998: 'The year the embassy bombings occurred in Kenya and Tanzania',
    1999: 'The year the Second Liberian Civil War began',
    2000: 'The year the Israeli withdrawal from Lebanon took place',
    2001: 'The year Wikipedia was launched',
    2002: 'The year the Euro entered circulation',
    2003: 'The year the supersonic transport Concorde made its final flight',
    2004: 'The year the Union of South American Nations was formed',
    2005: "The year Angela Merkel became Germany's first female Chancellor",
    2006: 'The year Nintendo launched the Wii',
    2007: 'The year the First Ivorian Civil War ended',
    2008: 'The year Spotify was launched',
    2009: 'The year the Second Chechen War ended',
    2010: 'The year the iPad was introduced',
    2011: 'The year the world population reached 7 billion',
    2012: 'The year the Higgs boson was discovered',
    2013: "The year Egyptian President Mohamed Morsi was ousted in a coup d'état",
    2014: 'The year Narendra Modi was elected as the Prime Minister of India',
    2015: 'The year the smart-contract-based cryptocurrency Ethereum was launched',
    2016: 'The year Fidel Castro died and received a state funeral',
    2017: "The year 'Oumuamua, the first known interstellar object, was identified",
    2018: 'The year Saudi Arabia allowed women to drive',
    2019: 'The year India revoked the special status of Jammu and Kashmir',
    2020: 'The year the United Kingdom formally withdrew from the European Union',
    2021: 'The year the African Continental Free Trade Area came into effect',
    2022: 'The year the Oder environmental disaster occurred',
    2023: 'The year the Catholic Church released Fiducia supplicans',
    2024: 'The year the Varzaqan helicopter crash took place',
}