general:
  work_dir: null
  dataset: null
  retrieval_metadata_path: null
  retrieval_model: null
  index_folder: null

retrieval:
  index:
    outfolder: null
    chunk_size: 200
    chunk_overlap: 20
    num_chunks: 1
    chunk_idx: 0
    batch_size: 32
  eval:
    batch_size: 32
    threads: 8


qa:
  max_num_contexts: 5
  outfolder: null
  local_llm_port: null
  local_llm_model: null
  use_retrieval_contexts: true
  minicheck_ckpt_path: "/scratch/lamdo/minicheck_ckpts"
  eval_only: false # if true, only do evaluation without generating answer again