general:
  work_dir: null
  dataset: null
  retrieval_metadata_path: null
  retrieval_model: null
  dataset_date: null
  index_folder: null

retrieval:
  index:
    outfolder: null
    chunk_size: 512
    chunk_overlap: 32
    num_chunks: 1
    chunk_idx: 0
    batch_size: 32
  eval:
    batch_size: 32
    threads: 8


qa:
  max_num_contexts: 5
  outfolder: null
  use_retrieval_contexts: true
  minicheck_ckpt_path: "/scratch/lamdo/minicheck_ckpts"
  eval_only: false # if true, only do evaluation without generating answer again
  use_chunk: true # if this is true, use top k retrieved chunks. If this is false, use the whole content from top k URL. Note: k is 'max_num_contexts'
  qa_llm_model_name: null
  eval_llm_model_name: gpt-4.1-mini


view:
  configurations: 
    - {keypoints: single}
    - {keypoints: multi}
    - {language: english_only}
    - {language: multilingual}
    - {freshness: 2024}
    - {freshness: 2025}
    - {topic: Culture}
    - {topic: Geography}
    - {topic: History_and_Society}
    - {topic: STEM}
    - {numhops: single}
    - {numhops: multi}
    # - {freshness: 2025, topic: Culture}
    # - {freshness: 2025, topic: Geography}
    # - {freshness: 2025, topic: History_and_Society}
    # - {freshness: 2025, topic: STEM}
    # - {topic: Culture, language: multilingual}