general:
  work_dir: null
  dataset: null
  retrieval_metadata_path: null
  retrieval_model: null
  dataset_date: null
  index_folder: null
  wikidump_date: 2026-03-01 # YYYY-MM-DD

retrieval:
  index:
    outfolder: null
    chunk_size: 256
    chunk_overlap: 0
    batch_size: 8
  eval:
    batch_size: 8
    threads: 8


qa:
  max_num_contexts: 5 # 5 is default
  outfolder: null
  use_retrieval_contexts: true
  minicheck_ckpt_path: "/scratch/lamdo/minicheck_ckpts"
  eval_only: false # if true, only do evaluation without generating answer again
  use_chunk: true # if this is true, use top k retrieved chunks. If this is false, use the whole content from top k URL. Note: k is 'max_num_contexts'
  qa_llm_model_name: null
  eval_llm_model_name: gpt-4.1
  eval_llm2_model_name: null #qwen3-next-80B-A3B

  deep_research:
    max_search_calls: 10
    max_iterations: 10


adv_collection:
  llm_model_name: gpt-4.1-mini
  retrieval_model: text-embedding-3-small


view:
  configurations: 
    - {false_premise: false, language: english_only}
    - {false_premise: false, language: multilingual}
    - {false_premise: false, freshness: 2024}
    - {false_premise: false, freshness: 2025}
    - {false_premise: false, freshness: 2026}
    - {false_premise: false, topic: Culture}
    - {false_premise: false, topic: Geography}
    - {false_premise: false, topic: History_and_Society}
    - {false_premise: false, topic: STEM}
    - {false_premise: false, numhops: 1}
    - {false_premise: false, numhops: 2}
    - {false_premise: false, numhops: 3}
    - {false_premise: true}
    # - {false_premise: true, freshness: 2025}
    # - {false_premise: false, freshness: 2024, numhops: 1}
    # - {false_premise: false, freshness: 2024, numhops: 2}
    # - {false_premise: false, freshness: 2025, numhops: 1}
    # - {false_premise: false, freshness: 2025, numhops: 2}
    # - {false_premise: false, topic: Culture, numhops: 1, language: english_only}
    # - {false_premise: false, topic: Geography, numhops: 1, language: english_only}
    # - {false_premise: false, topic: History_and_Society, numhops: 1, language: english_only}
    # - {false_premise: false, topic: STEM, numhops: 1, language: english_only}